In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

In [2]:
df = pd.read_csv('../DATA/Featured_Data/gurgaon_properties_post_feature_selection_v2.csv').drop(columns=['store room','floor_category','balcony'])

In [3]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,flat,sector 36,0.82,3.0,2.0,New Property,850.0,0.0,0.0,Low
1,flat,sector 89,0.95,2.0,2.0,New Property,1226.0,1.0,0.0,Low
2,flat,sohna road,0.32,2.0,2.0,New Property,1000.0,0.0,0.0,Low
3,flat,sector 92,1.60,3.0,4.0,Relatively New,1615.0,1.0,1.0,High
4,flat,sector 102,0.48,2.0,2.0,Relatively New,582.0,0.0,0.0,High

In [554]:
# 0 -> unfurnished
# 1 -> semifurnished
# 2 -> furnished

In [594]:
# Numerical = bedRoom, bathroom, built_up_area, servant room
# Ordinal = property_type, furnishing_type, luxury_category 
# OHE = sector, agePossession

In [4]:
df['agePossession'] = df['agePossession'].replace(
    {
        'Relatively New':'new',
        'Moderately Old':'old',
        'New Property' : 'new',
        'Old Property' : 'old',
        'Under Construction' : 'under construction'
    }
)

In [5]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,flat,sector 36,0.82,3.0,2.0,new,850.0,0.0,0.0,Low
1,flat,sector 89,0.95,2.0,2.0,new,1226.0,1.0,0.0,Low
2,flat,sohna road,0.32,2.0,2.0,new,1000.0,0.0,0.0,Low
3,flat,sector 92,1.60,3.0,4.0,new,1615.0,1.0,1.0,High
4,flat,sector 102,0.48,2.0,2.0,new,582.0,0.0,0.0,High

In [6]:
df['property_type'] = df['property_type'].replace({'flat':0,'house':1})

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_13976\71934247.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['property_type'] = df['property_type'].replace({'flat':0,'house':1})

In [7]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,0,sector 36,0.82,3.0,2.0,new,850.0,0.0,0.0,Low
1,0,sector 89,0.95,2.0,2.0,new,1226.0,1.0,0.0,Low
2,0,sohna road,0.32,2.0,2.0,new,1000.0,0.0,0.0,Low
3,0,sector 92,1.60,3.0,4.0,new,1615.0,1.0,1.0,High
4,0,sector 102,0.48,2.0,2.0,new,582.0,0.0,0.0,High

In [8]:
df['luxury_category'] = df['luxury_category'].replace({'Low':0,'Medium':1,'High':2})

C:\Users\SAHIL\AppData\Local\Temp\ipykernel_13976\2576796079.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['luxury_category'] = df['luxury_category'].replace({'Low':0,'Medium':1,'High':2})

In [9]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,built_up_area,servant room,furnishing_type,luxury_category
0,0,sector 36,0.82,3.0,2.0,new,850.0,0.0,0.0,0
1,0,sector 89,0.95,2.0,2.0,new,1226.0,1.0,0.0,0
2,0,sohna road,0.32,2.0,2.0,new,1000.0,0.0,0.0,0
3,0,sector 92,1.60,3.0,4.0,new,1615.0,1.0,1.0,2
4,0,sector 102,0.48,2.0,2.0,new,582.0,0.0,0.0,2

In [10]:
new_df = pd.get_dummies(df,columns=['sector','agePossession'],drop_first=True)

In [11]:
new_df.head()

,property_type,price,bedRoom,bathroom,built_up_area,servant room,furnishing_type,luxury_category,sector_gwal pahari,sector_manesar,...,sector_sector 9,sector_sector 90,sector_sector 91,sector_sector 92,sector_sector 93,sector_sector 95,sector_sector 99,sector_sohna road,agePossession_old,agePossession_under construction
0,0,0.82,3.0,2.0,850.0,0.0,0.0,0,False,False,...,False,False,False,False,False,False,False,False,False,False
1,0,0.95,2.0,2.0,1226.0,1.0,0.0,0,False,False,...,False,False,False,False,False,False,False,False,False,False
2,0,0.32,2.0,2.0,1000.0,0.0,0.0,0,False,False,...,False,False,False,False,False,False,False,True,False,False
3,0,1.60,3.0,4.0,1615.0,1.0,1.0,2,False,False,...,False,False,False,True,False,False,False,False,False,False
4,0,0.48,2.0,2.0,582.0,0.0,0.0,2,False,False,...,False,False,False,False,False,False,False,False,False,False

In [12]:
X = new_df.drop(columns=['price'])
y = new_df['price']

In [13]:
y_log = np.log1p(y)

In [14]:
y_log

0       0.598837
1       0.667829
2       0.277632
3       0.955511
4       0.392042
          ...
3549    0.314811
3550    1.945910
3551    0.470004
3552    2.803360
3553    1.022451
Name: price, Length: 3554, dtype: float64

In [15]:
X

,property_type,bedRoom,bathroom,built_up_area,servant room,furnishing_type,luxury_category,sector_gwal pahari,sector_manesar,sector_sector 1,...,sector_sector 9,sector_sector 90,sector_sector 91,sector_sector 92,sector_sector 93,sector_sector 95,sector_sector 99,sector_sohna road,agePossession_old,agePossession_under construction
0,0,3.0,2.0,850.0,0.0,0.0,0,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,0,2.0,2.0,1226.0,1.0,0.0,0,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,0,2.0,2.0,1000.0,0.0,0.0,0,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,0,3.0,4.0,1615.0,1.0,1.0,2,False,False,False,...,False,False,False,True,False,False,False,False,False,False
4,0,2.0,2.0,582.0,0.0,0.0,2,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3549,0,2.0,2.0,532.0,0.0,0.0,1,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3550,1,5.0,5.0,6228.0,1.0,0.0,2,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3551,0,1.0,1.0,665.0,0.0,1.0,1,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3552,1,5.0,6.0,5490.0,1.0,0.0,1,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3553,0,3.0,3.0,1845.0,0.0,1.0,1,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [16]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [17]:
X_scaled = pd.DataFrame(X_scaled,columns=X.columns)

In [18]:
X_scaled

,property_type,bedRoom,bathroom,built_up_area,servant room,furnishing_type,luxury_category,sector_gwal pahari,sector_manesar,sector_sector 1,...,sector_sector 9,sector_sector 90,sector_sector 91,sector_sector 92,sector_sector 93,sector_sector 95,sector_sector 99,sector_sohna road,agePossession_old,agePossession_under construction
0,-0.517180,-0.074329,-0.874300,-0.831662,-0.747968,-0.668281,-0.984642,-0.071348,-0.093805,-0.041123,...,-0.078923,-0.160267,-0.069328,-0.170153,-0.050386,-0.125375,-0.109357,-0.219245,-0.602271,-0.290738
1,-0.517180,-0.877269,-0.874300,-0.522517,1.336956,-0.668281,-0.984642,-0.071348,-0.093805,-0.041123,...,-0.078923,-0.160267,-0.069328,-0.170153,-0.050386,-0.125375,-0.109357,-0.219245,-0.602271,-0.290738
2,-0.517180,-0.877269,-0.874300,-0.708333,-0.747968,-0.668281,-0.984642,-0.071348,-0.093805,-0.041123,...,-0.078923,-0.160267,-0.069328,-0.170153,-0.050386,-0.125375,-0.109357,4.561105,-0.602271,-0.290738
3,-0.517180,-0.074329,0.505173,-0.202684,1.336956,1.037949,1.866207,-0.071348,-0.093805,-0.041123,...,-0.078923,-0.160267,-0.069328,5.877074,-0.050386,-0.125375,-0.109357,-0.219245,-0.602271,-0.290738
4,-0.517180,-0.877269,-0.874300,-1.052010,-0.747968,-0.668281,1.866207,-0.071348,-0.093805,-0.041123,...,-0.078923,-0.160267,-0.069328,-0.170153,-0.050386,-0.125375,-0.109357,-0.219245,-0.602271,-0.290738
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3549,-0.517180,-0.877269,-0.874300,-1.093119,-0.747968,-0.668281,0.440783,-0.071348,-0.093805,-0.041123,...,-0.078923,-0.160267,-0.069328,-0.170153,-0.050386,-0.125375,-0.109357,-0.219245,-0.602271,-0.290738
3550,1.933563,1.531549,1.194909,3.590095,1.336956,-0.668281,1.866207,-0.071348,-0.093805,-0.041123,...,-0.078923,-0.160267,-0.069328,-0.170153,-0.050386,-0.125375,-0.109357,-0.219245,-0.602271,-0.290738
3551,-0.517180,-1.680208,-1.564036,-0.983768,-0.747968,1.037949,0.440783,-0.071348,-0.093805,-0.041123,...,-0.078923,-0.160267,-0.069328,-0.170153,-0.050386,-0.125375,-0.109357,-0.219245,1.660383,-0.290738
3552,1.933563,1.531549,1.884645,2.983317,1.336956,-0.668281,0.440783,-0.071348,-0.093805,-0.041123,...,-0.078923,-0.160267,-0.069328,-0.170153,-0.050386,-0.125375,-0.109357,-0.219245,1.660383,-0.290738
3553,-0.517180,-0.074329,-0.184564,-0.013579,-0.747968,1.037949,0.440783,-0.071348,-0.093805,-0.041123,...,-0.078923,-0.160267,-0.069328,-0.170153,-0.050386,-0.125375,-0.109357,-0.219245,-0.602271,-0.290738

In [19]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(LinearRegression(), X_scaled, y_log, cv=kfold, scoring='r2')

In [20]:
scores.mean(),scores.std()

(np.float64(0.8512613057405425), np.float64(0.016992929105286228))

In [21]:
lr = LinearRegression()

In [23]:
lr.fit(X_scaled, y_log)

LinearRegression()

In [24]:
lr.coef_

array([ 1.20165036e-01,  5.40015778e-02,  6.51193988e-02,  2.10637561e-01,
        5.09461847e-02,  8.28171481e-03,  6.18569187e-03,  9.81917509e-03,
       -2.27136751e-02, -5.19263751e-03,  5.24027544e-03,  2.69999569e-02,
       -2.90628642e-03,  1.96385005e-03, -1.93922433e-02,  5.72258238e-04,
       -1.29872300e-02,  1.68170547e-02,  2.61496408e-02, -1.49660399e-02,
        8.73379008e-03,  1.62286944e-02,  3.08257676e-02,  3.21709327e-02,
       -1.94575986e-02, -1.22503903e-02,  2.87410970e-02,  3.29139011e-03,
        1.39170889e-02,  6.72176140e-03, -9.41789321e-03,  3.54737020e-02,
        2.19599278e-03,  1.77019789e-02,  5.75604298e-02,  7.38834785e-02,
        6.74158385e-03,  4.18540805e-02, -1.27147058e-02,  6.27615381e-03,
        2.24917111e-02,  2.59569793e-02,  2.49451572e-03, -1.14658162e-02,
        1.14313378e-03,  1.21374481e-02,  2.57701788e-03, -2.07745570e-02,
        7.65349283e-03,  1.67856368e-02,  6.03752164e-02,  2.69570318e-02,
        1.58617969e-02,  1.28598727e-02,  5.41626440e-02,  3.17430014e-02,
       -1.72297943e-02,  7.18216283e-02,  2.10443533e-04,  4.84749150e-03,
        4.77635759e-02,  4.56437329e-02,  1.26161821e-02,  1.18773664e-02,
        2.52303521e-02,  2.36031705e-02,  3.18204019e-02, -1.57485005e-02,
        2.39413014e-02,  3.67191438e-02,  4.29101570e-02,  3.48405339e-02,
        2.35614842e-02,  7.10460874e-02,  5.28297760e-02,  4.09188005e-02,
        8.67820177e-03,  1.09346552e-02,  1.84268932e-02, -7.30098670e-03,
        5.52018115e-03,  1.71630841e-02, -3.27102156e-03,  3.02311567e-02,
       -1.43929417e-03,  2.21769328e-02,  2.57118679e-04,  7.78019604e-04,
       -4.29412787e-03,  1.31668013e-02, -1.34625877e-02,  1.98887698e-04,
        1.56836833e-02,  5.83181285e-04,  9.75235369e-03, -1.08282478e-03,
       -1.02957577e-02,  8.74730811e-03, -3.67080666e-03, -5.96770574e-05,
        8.60108585e-03,  2.02197856e-03, -1.32886614e-02, -1.29774114e-02,
       -1.20407225e-04, -2.85559210e-02, -3.97137146e-03, -2.52221082e-02,
       -1.03122117e-02, -2.95146415e-02, -7.89967670e-03,  1.53813156e-02])

In [25]:
lr.coef_.shape

(112,)

In [31]:
coef_df = pd.DataFrame(lr.coef_.reshape(1,112),columns=X.columns).stack().reset_index().drop(columns='level_0').rename(columns={'level_1':'Feature',0:'Coef'})
coef_df

                              Feature      Coef
0                       property_type  0.120165
1                             bedRoom  0.054002
2                            bathroom  0.065119
3                       built_up_area  0.210638
4                        servant room  0.050946
..                                ...       ...
107                  sector_sector 95 -0.025222
108                  sector_sector 99 -0.010312
109                 sector_sohna road -0.029515
110                 agePossession_old -0.007900
111  agePossession_under construction  0.015381

[112 rows x 2 columns]

In [32]:
y_log.std()

np.float64(0.5579613263072812)

In [33]:
X['bedRoom'].std()

np.float64(1.2455995038118572)

In [42]:
0.054 * (y_log.std()/X['bedRoom'].std())

np.float64(0.02418908447569853)

In [46]:
np.expm1(0.054 * (y_log.std()/X['bedRoom'].std()))

np.float64(0.024484013600191708)

In [48]:
np.expm1( 0.210638  * (y_log.std()/X['built_up_area'].std()))

np.float64(9.662172747465983e-05)

In [ ]:
coef_df = pd.DataFrame(ridge.coef_.reshape(1,112),columns=X.columns).stack().reset_index().drop(columns=['level_0']).rename(columns={'level_1':'feature',0:'coef'})

In [675]:
lr = LinearRegression()
ridge = Ridge(alpha=0.0001)

In [628]:
lr.fit(X_scaled,y_log)

LinearRegression()

In [676]:
ridge.fit(X_scaled,y_log)

Ridge(alpha=0.0001)

In [677]:
coef_df = pd.DataFrame(ridge.coef_.reshape(1,112),columns=X.columns).stack().reset_index().drop(columns=['level_0']).rename(columns={'level_1':'feature',0:'coef'})

In [678]:
coef_df

                              feature      coef
0                       property_type  0.120165
1                             bedRoom  0.054002
2                            bathroom  0.065119
3                       built_up_area  0.210638
4                        servant room  0.050946
..                                ...       ...
107                  sector_sector 95 -0.025222
108                  sector_sector 99 -0.010312
109                 sector_sohna road -0.029515
110                 agePossession_old -0.007900
111  agePossession_under construction  0.015381

[112 rows x 2 columns]

In [640]:
# 1. Import necessary libraries
import statsmodels.api as sm

# 2. Add a constant to X
X_with_const = sm.add_constant(X_scaled)

# 3. Fit the model
model = sm.OLS(y_log, X_with_const).fit()

# 4. Obtain summary statistics
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.865
Model:                            OLS   Adj. R-squared:                  0.860
Method:                 Least Squares   F-statistic:                     196.7
Date:                Tue, 26 Sep 2023   Prob (F-statistic):               0.00
Time:                        20:35:17   Log-Likelihood:                 588.22
No. Observations:                3554   AIC:                            -950.4
Df Residuals:                    3441   BIC:                            -252.6
Df Model:                         112
Covariance Type:            nonrobust
====================================================================================================
                                       coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------
const                                1.0464      0.003    299.336      0.000       1.040       1.053
property_type                        0.1202      0.005     22.829      0.000       0.110       0.130
bedRoom                              0.0540      0.007      8.196      0.000       0.041       0.067
bathroom                             0.0651      0.007      9.554      0.000       0.052       0.078
built_up_area                        0.2106      0.005     41.763      0.000       0.201       0.221
servant room                         0.0509      0.005     11.231      0.000       0.042       0.060
furnishing_type                      0.0083      0.004      2.038      0.042       0.000       0.016
luxury_category                      0.0062      0.004      1.534      0.125      -0.002       0.014
sector_gwal pahari                   0.0098      0.006      1.551      0.121      -0.003       0.022
sector_manesar                      -0.0227      0.008     -2.922      0.004      -0.038      -0.007
sector_sector 1                     -0.0052      0.005     -1.116      0.264      -0.014       0.004
sector_sector 10                     0.0052      0.005      1.088      0.277      -0.004       0.015
sector_sector 102                    0.0270      0.013      2.049      0.041       0.001       0.053
sector_sector 103                   -0.0029      0.009     -0.332      0.740      -0.020       0.014
sector_sector 104                    0.0020      0.011      0.184      0.854      -0.019       0.023
sector_sector 105                   -0.0194      0.007     -2.926      0.003      -0.032      -0.006
sector_sector 106                    0.0006      0.008      0.068      0.946      -0.016       0.017
sector_sector 107                   -0.0130      0.010     -1.283      0.200      -0.033       0.007
sector_sector 108                    0.0168      0.010      1.674      0.094      -0.003       0.037
sector_sector 109                    0.0261      0.012      2.182      0.029       0.003       0.050
sector_sector 11                    -0.0150      0.006     -2.442      0.015      -0.027      -0.003
sector_sector 110                    0.0087      0.007      1.262      0.207      -0.005       0.022
sector_sector 111                    0.0162      0.007      2.392      0.017       0.003       0.030
sector_sector 112                    0.0308      0.007      4.445      0.000       0.017       0.044
sector_sector 113                    0.0322      0.009      3.644      0.000       0.015       0.049
sector_sector 12                    -0.0195      0.008     -2.469      0.014      -0.035      -0.004
sector_sector 13                    -0.0123      0.005     -2.372      0.018      -0.022      -0.002
sector_sector 14                     0.0287      0.006      4.504      0.000       0.016       0.041
sector_sector 15                     0.0033      0.005      0.707      0.480      -0.006       0.012
sector_sector 17                     0.0139      0.005      2.624      0.009       0.004       0.024
sector_sector 2                      0.0067      0.010      0.651      0.515      -0.014       0.027
sector_sector 21                    -0.0094      0.005     -2.022      0.043      -0.019      -0.000
sector_sector 22                     0.0355      0.007      5.395      0.000       0.023       0.048
sector_sector 23                     0.0022      0.006      0.383      0.702      -0.009       0.013
sector_sector 24                     0.0177      0.007      2.678      0.007       0.005       0.031
sector_sector 25                     0.0576      0.008      6.842      0.000       0.041       0.074
sector_sector 26                     0.0739      0.009      8.494      0.000       0.057       0.091
sector_sector 27                     0.0067      0.004      1.712      0.087      -0.001       0.014
sector_sector 28                     0.0419      0.009      4.908      0.000       0.025       0.059
sector_sector 3                     -0.0127      0.007     -1.804      0.071      -0.027       0.001
sector_sector 30                     0.0063      0.004      1.398      0.162      -0.003       0.015
sector_sector 31                     0.0225      0.005      4.243      0.000       0.012       0.033
sector_sector 33                     0.0260      0.011      2.443      0.015       0.005       0.047
sector_sector 36                     0.0025      0.007      0.367      0.713      -0.011       0.016
sector_sector 37                    -0.0115      0.010     -1.201      0.230      -0.030       0.007
sector_sector 37d                    0.0011      0.010      0.110      0.912      -0.019       0.021
sector_sector 38                     0.0121      0.005      2.291      0.022       0.002       0.023
sector_sector 39                     0.0026      0.005      0.474      0.635      -0.008       0.013
sector_sector 4                     -0.0208      0.009     -2.286      0.022      -0.039      -0.003
sector_sector 40                     0.0077      0.004      1.701      0.089      -0.001       0.016
sector_sector 41                     0.0168      0.005      3.074      0.002       0.006       0.027
sector_sector 43                     0.0604      0.010      5.977      0.000       0.041       0.080
sector_sector 45                     0.0270      0.005      5.397      0.000       0.017       0.037
sector_sector 46                     0.0159      0.005      2.898      0.004       0.005       0.027
sector_sector 47                     0.0129      0.006      2.106      0.035       0.001       0.025
sector_sector 48                     0.0542      0.010      5.476      0.000       0.035       0.074
sector_sector 49                     0.0317      0.009      3.509      0.000       0.014       0.049
sector_sector 5                     -0.0172      0.007     -2.568      0.010      -0.030      -0.004
sector_sector 50                     0.0718      0.010      6.921      0.000       0.051       0.092
sector_sector 51                     0.0002      0.005      0.044      0.965      -0.009       0.010
sector_sector 52                     0.0048      0.006      0.830      0.407      -0.007       0.016
sector_sector 53                     0.0478      0.006      8.223      0.000       0.036       0.059
sector_sector 54                     0.0456      0.007      6.273      0.000       0.031       0.060
sector_sector 55                     0.0126      0.005      2.382      0.017       0.002       0.023
sector_sector 56                     0.0119      0.010      1.223      0.221      -0.007       0.031
sector_sector 57                     0.0252      0.007      3.616      0.000       0.012       0.039
sector_sector 58                     0.0236      0.005      4.908      0.000       0.014       0.033
sector_sector 59                     0.0318      0.005      6.431      0.000       0.022       0.042
sector_sector 6                     -0.0157      0.005     -2.892      0.004      -0.026      -0.005
sector_sector 60                     0.0239      0.006      4.010      0.000       0.012       0.036
sector_sector 61                     0.0367      0.009      4.262      0.000       0.020       0.054
sector_sector 62                     0.0429      0.006      7.056      0.000       0.031       0.055
sector_sector 63                     0.0348      0.006      5.985      0.000       0.023       0.046
sector_sector 63a                    0.0236      0.006      3.976      0.000       0.012       0.035
sector_sector 65                     0.0710      0.012      5.926      0.000       0.048       0.095
sector_sector 66                     0.0528      0.009      6.072      0.000       0.036       0.070
sector_sector 67                     0.0409      0.009      4.444      0.000       0.023       0.059
sector_sector 67a                    0.0087      0.007      1.300      0.194      -0.004       0.022
sector_sector 68                     0.0109      0.008      1.433      0.152      -0.004       0.026
sector_sector 69                     0.0184      0.012      1.487      0.137      -0.006       0.043
sector_sector 7                     -0.0073      0.008     -0.889      0.374      -0.023       0.009
sector_sector 70                     0.0055      0.009      0.592      0.554      -0.013       0.024
sector_sector 70a                    0.0172      0.010      1.760      0.078      -0.002       0.036
sector_sector 71                    -0.0033      0.007     -0.445      0.656      -0.018       0.011
sector_sector 72                     0.0302      0.008      3.993      0.000       0.015       0.045
sector_sector 73                    -0.0014      0.004     -0.350      0.726      -0.009       0.007
sector_sector 74                     0.0222      0.006      3.496      0.000       0.010       0.035
sector_sector 76                     0.0003      0.006      0.043      0.965      -0.011       0.012
sector_sector 77                     0.0008      0.007      0.106      0.916      -0.014       0.015
sector_sector 78                    -0.0043      0.006     -0.706      0.480      -0.016       0.008
sector_sector 79                     0.0132      0.011      1.166      0.244      -0.009       0.035
sector_sector 8                     -0.0135      0.005     -2.782      0.005      -0.023      -0.004
sector_sector 80                     0.0002      0.004      0.044      0.965      -0.009       0.009
sector_sector 81                     0.0157      0.012      1.304      0.192      -0.008       0.039
sector_sector 82                     0.0006      0.009      0.067      0.946      -0.016       0.018
sector_sector 82a                    0.0098      0.006      1.510      0.131      -0.003       0.022
sector_sector 83                    -0.0011      0.011     -0.100      0.920      -0.022       0.020
sector_sector 84                    -0.0103      0.009     -1.101      0.271      -0.029       0.008
sector_sector 85                     0.0087      0.013      0.662      0.508      -0.017       0.035
sector_sector 86                    -0.0037      0.010     -0.355      0.722      -0.024       0.017
sector_sector 88                 -5.968e-05      0.004     -0.015      0.988      -0.008       0.008
sector_sector 88a                    0.0086      0.007      1.266      0.206      -0.005       0.022
sector_sector 89                     0.0020      0.010      0.204      0.838      -0.017       0.021
sector_sector 9                     -0.0133      0.007     -1.943      0.052      -0.027       0.000
sector_sector 90                    -0.0130      0.012     -1.070      0.285      -0.037       0.011
sector_sector 91                    -0.0001      0.006     -0.019      0.985      -0.012       0.012
sector_sector 92                    -0.0286      0.013     -2.240      0.025      -0.054      -0.004
sector_sector 93                    -0.0040      0.005     -0.776      0.438      -0.014       0.006
sector_sector 95                    -0.0252      0.010     -2.568      0.010      -0.044      -0.006
sector_sector 99                    -0.0103      0.009     -1.180      0.238      -0.027       0.007
sector_sohna road                   -0.0295      0.016     -1.854      0.064      -0.061       0.002
agePossession_old                   -0.0079      0.005     -1.586      0.113      -0.018       0.002
agePossession_under construction     0.0154      0.004      3.796      0.000       0.007       0.023
==============================================================================
Omnibus:                      514.316   Durbin-Watson:                   1.937
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4724.056
Skew:                          -0.385   Prob(JB):                         0.00
Kurtosis:                       8.595   Cond. No.                         40.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [641]:
y_log.std()

0.5579613263072782

In [682]:
X_scaled['bedRoom'].std()

1.0001407162464122

In [683]:
0.21 * (0.557/1)

0.11697

In [681]:
np.expm1(0.030)

0.030454533953516858

In [653]:
2.4726962617564903e-05 * 100

0.0024726962617564905